language: c++
sudo: required
dist: trusty
services:
- docker
osx_image: xcode8.2

matrix:
  include:
  - os: linux
    env: IMAGE=hwcrypto-debian-testing-builder
  - os: linux
    env: IMAGE=hwcrypto-ubuntu-16.04-builder
  - os: linux
    env: IMAGE=hwcrypto-ubuntu-16.10-builder
  - os: linux
    env: IMAGE=hwcrypto-ubuntu-17.04-builder
  - os: linux
    env: IMAGE=hwcrypto-fedora-25-builder
  - os: osx

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull martinpaljak/${IMAGE}; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install qt5; fi
- if [[ "$TRAVIS_BRANCH" == "coverity_scan" ]]; then sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y; sudo apt-get update; sudo apt-get install -y qt56base qt56tools devscripts debhelper libdistro-info-perl libparse-debcontrol-perl libpcsclite-dev; export PATH=/opt/qt56/bin:${PATH}; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -e TRAVIS_COMMIT=${TRAVIS_COMMIT} -v ${PWD}:/artifacts martinpaljak/${IMAGE}; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export QTPATH=/usr/local/opt/qt5; make pkg; fi

env:
  global:
  - secure: FinTgZXFnVQc9JuFN7xEOna0ZNkquqVb64wPjrvim95V2AchQ4vUmo23itc0ga7hXyxWAS45H0ehXDlgmnKeeeZpBmPFmd8Expos05nX26AWw41Tho/gVSronBmGhcNuNM50PtJugdUErsQS4nYKHJJp0ujd0DeNCggHtVU+JSXpRFapjOux0HtRtvrLupEA0NQOjj8Tn8TKqxtVbAJ8Z87XlUbehfW2EHGVhY8sRlBqAJLAZdi+9Lw+ka9/qqa0Da8/P8R1dljdcH6+etyi84PNfOAqGO4uQaCJtX9EYiQGUX4XwHKwtd3pcZsPa+t6KTG39Cf2WeYOCtjlJTkW9uIm9QnqRKrxRDvWNZ0ARbKPdlO3UV+dRm6whrjFNdgBs+DQBWWQSHqdRGh+PliTErB3WrDRS4fkyIqa5mfIuwI4qYrkQy8I0sCCyUPbOCF8mG+EBrjw+e+OcbiSSeTwIJEv3oZaJ57Xy/jM2pHslHA5KPPpJgCakrvzwrsZzDcMNj0FfNrgxg1Zl3DoOmRxEUbFAFP6s1pg9xXxTlziI1S8obRRAL+N64L8aGLl9N+5ONGlEwjQBGRy5mYDCHxkXLh8faw/SjEocnCYspgNPUzEXX7Kd7IBQkBMF5Ht9P2+GscNBbc9U2ErSwRepl2lOWUuCq+M1PJi/L2WU57qQ00=
addons:
  coverity_scan:
    project:
      name: web-eid/web-eid
    notification_email: hwcrypto@googlegroups.com
    build_command: make
    branch_pattern: coverity_scan
deploy:
  provider: releases
  api-key:
    secure: btSrL3fhWeSfVsYiaDR2WJQPD8FGjJyQ5TrK8m0mOhUEAgY6nXYggJ8JbR4xnZPxVbrFNOWhAyViNMRd7R2LalaiTsCBYDhpN4ntUKqzEg/58gXWT2JjjhauhrcYuQxszqha4Vc3QvCNGFBozZO8whtqLzZ5h+nHzrSZMlvItg6erL0eGl6hIwSUqfJKTj3wm5EiESYiz6nS+WSJWurPjTx3j5I36p5M9e62wqT2o1QdBfcNVkyaqMeE2dwHwHSTuMA63qcikqdNR1zihl2lDgAdl7iBdCCR+cdt9AKbrjpcOCnOo7DkWtQxO/tRsa6WXAu5Rv0AW78LkRRiBxysTXp1qdFvmczen98TE18hfWRT+59a7Fw/M9TutITTF2MyQIPC0TbKG8+MzvpuzXzk4EaK7X0DtH+azNvyw6yAc3hb4+Gh7pKo1JjiLx6k77YNM6lmqS9Ay50zLSTfo5xkauOyD+GYeaTlcekJVLuMSt5miO4+whwDRx05lgDlwMeXiWFI3wnfxEfXHF/cqmDcUwn+V2CfaS0s97ylRdr/WyShaNoyRqlXqQksBl8fAGKaKGAE/4K5t5gtkAviwLemejd/TkeqS2p5CxfeAhVJzf+XE2+GuR9KtkDgq4kRn7kBZ4v6+baTBTQbb06xU/gpMst1Ojpsj6Xt7+Rn/f0BcQw=
  file_glob: true
  file:
    - Web-eID_*.pkg
    - web-eid_*.deb
    - web-eid*.rpm
  skip_cleanup: true
  on:
    tags: true
