osx_image: xcode8.2
sudo: true
dist: trusty
language: c

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openssl; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then fakeroot debian/rules binary; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make pkg OPENSSL=/usr/local/Cellar/openssl/1.0.2j; fi

os:
- linux
- osx
env:
  global:
  - secure: "eQphLF0NVr0L9ZBF0GhLfVo1qOAVfmewIMt8a+/AZTryUvP86fx5YvbykNmO1wJszvJiMW82hQaLhVS9Acw90v7Gm54plM7+5maqIHatD/cO3cz0DmlzItP+RqRv8VdNNSlsPtBsmA1nlIQOajFYJt1TCCT0P/fHk9l/19uBn/cYUy4QaHJIDzNSyWykZfQBj4KJj+ebVH1soGSwOBMiaEn5qAAYMiSgL1ZRBGNQYd1/J++0NufOLcLXEqL0sVGb6an+yfu4ydMPFigmZRrDBUMq0oUr5lp6cL0P2TS9rZDSQ0oF7bBY0M2Zi/UmtpVC6ahJzuJcl3ethnuiYl/QDZJNwMdaws07Km6wIFgxSnDu9nId2kbLq5jGp3VrEaZV8CDy2ABbsbnsxOCPieOOwHLePpk/lIA7tnP+aBwNpB40hSdF5yzW3+HO1AFQXtJHTefdhn++OlR2mXG8EDVW6F33lTGp/3Mh9xo1Q09vnDpA87c7R7ERUn+Ga2WYogbphDuRCxsqo+Y17SJVLIqdhwd1HMRbDZmXv6xgNuLQv5v426cCc1LKpNFzlSre3r+pcveDOi3IPcp+w0vcwpSgF9kS8bZnLPKZhpyMJHpvG+a/uJ0S4hr+E4hHl+K3VLmigrxv5QRxHXATBv+Xg3g0SAKD0r9vLt0wWzJp6f/W57w="
addons:
  apt:
    packages:
    - debhelper
    - devscripts
    - qtbase5-dev
    - qttools5-dev
    - qttools5-dev-tools
    - libssl-dev
    - libpcsclite-dev
  coverity_scan:
    project:
      name: hwcrypto/hwcrypto-native
    notification_email: hwcrypto@googlegroups.com
    build_command_prepend: 
    build_command: make
    branch_pattern: coverity_scan
